<template>
<div class="contacts-page">
<div class="contacts-header"><b>联系人</b><span>{{ contacts.length }} 人</span><Icon class="refresh" icon="ion:reload" width="18" height="18" @click="load" /></div>
<div class="contacts-body"><div class="contact-list" v-loading="loading">
<div v-for="item in contacts" :key="item.email" class="contact-row" :class="{active:selectedEmail===item.email}" @click="selectedEmail=item.email"><div class="avatar">{{ avatarText(item.displayName) }}</div><div class="contact-main"><div class="contact-name">{{ item.displayName }}</div><div class="contact-email">{{ item.email }}</div></div><span class="mail-count">{{ item.mailCount }}</span><Icon icon="material-symbols:edit-outline" width="18" height="18" class="edit" @click.stop="editContact(item)" /></div>
<el-empty v-if="!loading && !contacts.length" description="暂无联系人" /></div>
<div class="mail-panel"><template v-if="selected"><div class="detail-header"><div><div class="detail-name">{{ selected.displayName }}</div><div class="detail-email">{{ selected.email }}</div></div><el-button size="small" @click="editContact(selected)">编辑联系人</el-button></div><div class="mail-list"><div v-for="mail in selectedMails" :key="mail.emailId" class="mail-row"><div class="mail-subject">{{ mail.subject || '(无主题)' }}</div><div class="mail-time">{{ formatDetailDate(mail.createTime) }}</div><div class="mail-preview">{{ mail.text || '' }}</div></div><el-empty v-if="!selectedMails.length" description="没有找到该联系人的来信" /></div></template><el-empty v-else description="选择一个联系人，查看他的全部来信" /></div></div>
<el-dialog v-model="dialogVisible" title="编辑联系人" width="420px"><div class="dialog-email">{{ editing?.email }}</div><el-input v-model="nicknameDraft" placeholder="昵称，例如 Pavel / POST" clearable /><template #footer><el-button @click="dialogVisible=false">取消</el-button><el-button type="primary" @click="saveContact">保存</el-button></template></el-dialog>
</div>
</template>
<script setup>
import { computed, onMounted, ref, watch } from 'vue'
import { Icon } from '@iconify/vue'
import { useAccountStore } from '@/store/account.js'
import { useContactStore } from '@/store/contact.js'
import { emailList } from '@/request/email.js'
import { formatDetailDate } from '@/utils/day.js'
const accountStore=useAccountStore(), contactStore=useContactStore(); const incoming=ref([]),loading=ref(false),selectedEmail=ref(''),dialogVisible=ref(false),editing=ref(null),nicknameDraft=ref('')
const contacts=computed(()=>{const map=new Map(contactStore.contacts(accountStore.currentAccountId).map(x=>[x.email.toLowerCase(),x]));for(const m of incoming.value){const email=String(m.sendEmail||'').trim();if(!email)continue;const k=email.toLowerCase();if(!map.has(k))map.set(k,{email,nickname:'',name:m.name||''});else if(!map.get(k).name&&m.name)map.get(k).name=m.name}return [...map.values()].map(x=>({...x,displayName:x.nickname||x.name||x.email,mailCount:incoming.value.filter(m=>String(m.sendEmail||'').toLowerCase()===x.email.toLowerCase()).length,lastTime:incoming.value.find(m=>String(m.sendEmail||'').toLowerCase()===x.email.toLowerCase())?.createTime||''})).sort((a,b)=>String(b.lastTime).localeCompare(String(a.lastTime)))})
const selected=computed(()=>contacts.value.find(x=>x.email.toLowerCase()===selectedEmail.value.toLowerCase())||null);const selectedMails=computed(()=>incoming.value.filter(m=>String(m.sendEmail||'').toLowerCase()===selectedEmail.value.toLowerCase()));function avatarText(v=''){const s=String(v).trim();return s?s[0].toUpperCase():'?'}
async function load(){if(!accountStore.currentAccountId)return;loading.value=true;try{const all=[];let cursor=9999999999,total=Infinity;while(all.length<total){const d=await emailList(accountStore.currentAccountId,0,cursor,0,50,0);const b=d.list||[];if(!b.length)break;all.push(...b);total=Number(d.total||all.length);const last=b[b.length-1];if(!last||last.emailId===cursor)break;cursor=last.emailId;if(b.length<50)break}incoming.value=all}finally{loading.value=false}}
function editContact(item){editing.value=item;nicknameDraft.value=item.nickname||'';dialogVisible.value=true}function saveContact(){if(!editing.value)return;contactStore.upsert(accountStore.currentAccountId,{email:editing.value.email,nickname:nicknameDraft.value.trim(),name:editing.value.name||''});dialogVisible.value=false}watch(()=>accountStore.currentAccountId,()=>{selectedEmail.value='';load()});onMounted(load)
</script>
<style scoped lang="scss">.contacts-page{height:100%;display:flex;flex-direction:column;overflow:hidden}.contacts-header{height:48px;flex:0 0 48px;display:flex;align-items:center;gap:10px;padding:0 16px;border-bottom:1px solid var(--light-border-color)}.contacts-header span{color:var(--secondary-text-color);font-size:13px}.refresh{margin-left:auto;cursor:pointer}.contacts-body{flex:1;display:grid;grid-template-columns:330px 1fr;min-height:0}.contact-list{overflow:auto;border-right:1px solid var(--light-border-color)}.contact-row{display:flex;align-items:center;gap:10px;padding:11px 14px;border-bottom:1px solid var(--light-border-color);cursor:pointer}.contact-row:hover,.contact-row.active{background:var(--light-ill)}.avatar{width:38px;height:38px;flex:0 0 38px;border-radius:50%;display:flex;align-items:center;justify-content:center;background:var(--el-color-primary-light-8);color:var(--el-color-primary);font-weight:700}.contact-main{min-width:0;flex:1}.contact-name,.contact-email{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.contact-name{font-weight:600}.contact-email,.mail-count{color:var(--secondary-text-color);font-size:12px}.mail-count{min-width:24px;text-align:right}.edit{cursor:pointer;color:var(--secondary-text-color)}.mail-panel{min-width:0;display:flex;flex-direction:column;overflow:hidden}.detail-header{padding:16px 20px;border-bottom:1px solid var(--light-border-color);display:flex;align-items:center;justify-content:space-between}.detail-name{font-size:19px;font-weight:700}.detail-email,.dialog-email{color:var(--secondary-text-color);font-size:13px;margin-top:4px}.mail-list{overflow:auto}.mail-row{padding:14px 20px;border-bottom:1px solid var(--light-border-color)}.mail-subject{font-weight:600}.mail-time{float:right;color:var(--secondary-text-color);font-size:12px}.mail-preview{margin-top:5px;color:var(--secondary-text-color);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.dialog-email{margin-bottom:12px}@media(max-width:767px){.contacts-body{grid-template-columns:1fr}.mail-panel{display:none}.contact-list{border-right:0}}</style>
